- name: nginx 
  hosts: web 
  become: yes 
  tasks:
  - name: install nginx 
    ansible.builtin.dnf:
      name: nginx 
      state: latest 
  - name: start nginx
    ansible.builtin.service:
      name: start nginx service 
      state: started 
      enabled: yes 
      
